"""
SentinelIQ — Database Models
All tables defined here. Run alembic to migrate.
"""
from datetime import datetime
from enum import Enum as PyEnum
from typing import Optional

from sqlalchemy import (
    Column, String, Integer, Float, Boolean, DateTime,
    ForeignKey, Text, Enum, JSON, Index
)
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import DeclarativeBase, relationship, sessionmaker

from config import settings


# ============================================================
# ENGINE & SESSION
# ============================================================
engine = create_async_engine(
    settings.DATABASE_URL,
    echo=settings.DEBUG,
    pool_size=10,
    max_overflow=20,
)

AsyncSessionLocal = sessionmaker(
    engine, class_=AsyncSession, expire_on_commit=False
)


async def get_db():
    """FastAPI dependency — yields a DB session"""
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise
        finally:
            await session.close()


async def init_db():
    """Create all tables on startup"""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


# ============================================================
# BASE
# ============================================================
class Base(DeclarativeBase):
    pass


# ============================================================
# ENUMS
# ============================================================
class SeverityLevel(str, PyEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, PyEnum):
    NEW = "NEW"
    INVESTIGATING = "INVESTIGATING"
    RESOLVED = "RESOLVED"
    FALSE_POSITIVE = "FALSE_POSITIVE"


class IncidentStatus(str, PyEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class LogSource(str, PyEnum):
    NETWORK = "NETWORK"       # Your LSTM / packet capture
    SYSLOG = "SYSLOG"         # Linux system logs
    AUTH = "AUTH"             # /var/log/auth.log
    WEB = "WEB"               # Apache/Nginx access logs
    HONEYPOT = "HONEYPOT"     # Cowrie honeypot


# ============================================================
# TABLE: normalized_logs
# Every log source goes through normalization and lands here
# ============================================================
class NormalizedLog(Base):
    __tablename__ = "normalized_logs"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    source = Column(Enum(LogSource), nullable=False, index=True)

    # Network fields
    src_ip = Column(String(45), index=True)   # IPv4 or IPv6
    dst_ip = Column(String(45))
    src_port = Column(Integer)
    dst_port = Column(Integer)
    protocol = Column(String(10))             # TCP, UDP, ICMP

    # Event fields
    event_type = Column(String(100))          # "failed_login", "port_scan", etc.
    username = Column(String(100))            # For auth events
    message = Column(Text)                    # Raw log line

    # ML prediction (if applicable)
    predicted_label = Column(String(100))     # "DoS Hulk", "BENIGN", etc.
    confidence = Column(Float)               # 0.0 - 1.0

    # Extra fields as JSON (flexible)
    extra = Column(JSON, default=dict)

    # Indexes for common queries
    __table_args__ = (
        Index("ix_logs_timestamp_source", "timestamp", "source"),
        Index("ix_logs_src_ip_timestamp", "src_ip", "timestamp"),
    )


# ============================================================
# TABLE: alerts
# Generated by the correlation engine
# ============================================================
class Alert(Base):
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # What happened
    title = Column(String(200), nullable=False)
    description = Column(Text)
    severity = Column(Enum(SeverityLevel), default=SeverityLevel.MEDIUM, index=True)
    status = Column(Enum(AlertStatus), default=AlertStatus.NEW, index=True)

    # Who did it
    src_ip = Column(String(45), index=True)
    dst_ip = Column(String(45))
    attack_type = Column(String(100), index=True)   # "DoS Hulk", "SSH Brute Force"

    # Detection details
    confidence = Column(Float)
    rule_id = Column(String(50))             # Which rule triggered this
    raw_log_id = Column(Integer, ForeignKey("normalized_logs.id"))

    # MITRE ATT&CK
    mitre_tactic = Column(String(100))       # "Initial Access"
    mitre_technique_id = Column(String(20))  # "T1110"
    mitre_technique_name = Column(String(200))  # "Brute Force"

    # Threat Intel enrichment
    ip_abuse_score = Column(Integer)         # 0-100 from AbuseIPDB
    ip_country = Column(String(5))           # "MA", "CN", "RU"
    ip_isp = Column(String(200))
    is_known_malicious = Column(Boolean, default=False)

    # Relationships
    incident_id = Column(Integer, ForeignKey("incidents.id"), nullable=True)
    incident = relationship("Incident", back_populates="alerts")

    __table_args__ = (
        Index("ix_alerts_created_severity", "created_at", "severity"),
        Index("ix_alerts_src_ip_type", "src_ip", "attack_type"),
    )


# ============================================================
# TABLE: incidents
# Group of related alerts = one incident
# ============================================================
class Incident(Base):
    __tablename__ = "incidents"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    resolved_at = Column(DateTime, nullable=True)

    title = Column(String(200), nullable=False)
    description = Column(Text)
    severity = Column(Enum(SeverityLevel), default=SeverityLevel.MEDIUM)
    status = Column(Enum(IncidentStatus), default=IncidentStatus.OPEN)

    # Kill chain stage (your IDS already detects these attack types)
    kill_chain_stage = Column(String(100))   # "Reconnaissance", "Exploitation", etc.

    # Analyst notes
    analyst_notes = Column(Text)
    assigned_to = Column(String(100))

    # Relationships
    alerts = relationship("Alert", back_populates="incident")
    timeline = relationship("TimelineEvent", back_populates="incident")


# ============================================================
# TABLE: timeline_events
# Ordered events per incident (for the investigation view)
# ============================================================
class TimelineEvent(Base):
    __tablename__ = "timeline_events"

    id = Column(Integer, primary_key=True)
    incident_id = Column(Integer, ForeignKey("incidents.id"), nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow)

    event_type = Column(String(100))     # "ALERT", "ACTION", "NOTE"
    description = Column(Text)
    actor = Column(String(100))          # IP or analyst username

    incident = relationship("Incident", back_populates="timeline")


# ============================================================
# TABLE: correlation_rules
# YAML-defined rules loaded into DB at startup
# ============================================================
class CorrelationRule(Base):
    __tablename__ = "correlation_rules"

    id = Column(Integer, primary_key=True)
    rule_id = Column(String(50), unique=True, nullable=False)
    name = Column(String(200), nullable=False)
    description = Column(Text)
    enabled = Column(Boolean, default=True)

    # Rule logic (stored as JSON)
    conditions = Column(JSON)    # threshold, window, event_type, etc.
    severity = Column(Enum(SeverityLevel))

    # MITRE mapping
    mitre_tactic = Column(String(100))
    mitre_technique_id = Column(String(20))
    mitre_technique_name = Column(String(200))

    created_at = Column(DateTime, default=datetime.utcnow)


# ============================================================
# TABLE: blocked_ips
# IPs blocked by auto-response playbooks
# ============================================================
class BlockedIP(Base):
    __tablename__ = "blocked_ips"

    id = Column(Integer, primary_key=True)
    ip_address = Column(String(45), unique=True, nullable=False)
    reason = Column(String(200))
    blocked_at = Column(DateTime, default=datetime.utcnow)
    blocked_by = Column(String(100))      # "AUTO" or analyst name
    alert_id = Column(Integer, ForeignKey("alerts.id"))
    is_active = Column(Boolean, default=True)
    expires_at = Column(DateTime, nullable=True)


# ============================================================
# TABLE: trusted_ips
# IPs dynamically whitelisted by analysts
# ============================================================
class TrustedIP(Base):
    __tablename__ = "trusted_ips"

    id = Column(Integer, primary_key=True)
    ip_prefix = Column(String(45), unique=True, nullable=False)
    description = Column(String(200))
    added_at = Column(DateTime, default=datetime.utcnow)
    added_by = Column(String(100), default="Admin")